services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dicoDingo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database:/data/db
  app-admin:
    image: 'padabou/dicodingo-admin:latest'
    ports:
      - 4000:8080
  app-admin-v2:
    image: 'padabou/dicodingo-admin2:latest'
    container_name: app-admin-v2
    ports:
      - 4000:3000
  app-front:
    image: 'padabou/dicodingo-front:latest'
    ports:
      - 3000:3000

  app-backend:
    image: 'padabou/dicodingo-backend:latest'
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - spring.data.mongodb.uri=mongodb://dicoDingoUser:example@mongo:27017/dicoDingo?Authsource=dicoDingo
      - server.tomcat.accesslog.enabled=true
      - spring.profiles.active=prod
      - app.cors.allowedOrigins=https://equidico.fr,https://www.equidico.fr
      - app.private.apikey=jogIjEyMzQ1Njc4OTAiLA0KI
